spring.application.name=peliculas
server.port=9525
spring.datasource.url=jdbc:postgresql://localhost:5432/db_peliculas
spring.datasource.username=postgres
spring.datasource.password=${PASSWORD_DB}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
# Log de Consola Senior (Muestra y formatea el SQL generado en caliente):
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET:EstaEsUnaClaveSecretaUltraSeguraYMuyLargaParaGarantizarLos256BitsExigidosPorElAlgoritmoDeFirma}
jwt.expiration=${JWT_EXPIRATION:3600000}